### ISSUE TITLE
TypeError: r is not a function

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/libsodium.js#211]
```js
const _sodium = require('libsodium-wrappers');
```

Loading the current `libsodium-wrappers` module in Git produces this:

```text
TypeError: r is not a function
    at process.wA (/Users/j/src/libsodium.js/node_modules/libsodium/dist/modules/libsodium.js:1:323138)
    at process.emit (events.js:203:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
```

NodeJS v12.8.1

**Comment by jedisct1** [comment]
Note that version 0.7.5 works.

Any idea?

**Comment by jedisct1** [comment]
Found the issue.

I had a `libsodium` module in `~/node_modules`, that was an older version than the one in the directory where `libsodium_wrappers` was.
