### ISSUE TITLE
Update builds for node Version 5

### ISSUE THREAD

**Issue by wanderer** [jedisct1/libsodium.js#40]
```
Module version mismatch. Expected 46, got 47.
App threw an error when running [Error: Module version mismatch. Expected 46, got 47.]
/home/null/code/patchwork/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filename);if(!ret&&filename!=nodePath["resolve"](filenam

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/null/code/patchwork/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/null/code/patchwork/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:434:26)
```

**Comment by jedisct1** [comment]
I don't think it has anything to do with libsodium.js, which doesn't use any modules with C code.

Looks like you had a previous version of node or iojs, then upgraded to node 5 without rebuilding the modules.

[npm-rebuild](https://docs.npmjs.com/cli/rebuild) should fix this.

**Comment by wanderer** [comment]
thanks!
