### ISSUE TITLE
Requiring libsodium eats exception stack traces in Node 6

### ISSUE THREAD

**Issue by juhoojala** [jedisct1/libsodium.js#59]
With the following `test.js`
```js
var libsodium = require('libsodium');
console.log('Hello');
throw Error('error');
```

Run in Node 6
```shell
$ nvm use 6
Now using node v6.2.0 (npm v3.8.9)
$ node test.js
/Users/jpo/Lucify/code/jep/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENV
```
There is no exception stack trace for the thrown error, and some unrelated sodium code instead.

With node 5 it is a bit better:
```
$ nvm use 5
Now using node v5.11.1 (npm v3.8.6)
$ node test.js
Hello
/Users/jpo/Lucify/code/jep/node_modules/libsodium/dist/modules/libsodium.js:14
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENV

Error: error
    at Error (native)
    at Object.<anonymous> (/Users/jpo/Lucify/code/jep/test.js:4:7)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

Now at least the exception stack trace is there. There is however also the weird code snippet from libsodium. Same for Node 4.

So somehow just requiring sodium takes over some of the exception handling in node.

The same thing happens with both libsodium versions `3.0.0` and `0.2.11`. I did the test with a fresh project created with `npm init`.

**Comment by BatikhSouri** [comment]
This affects also Node v5 and v0.10.

**Comment by jedisct1** [comment]
This is due to Emscripten generating a handler for `uncaughtException` events. This is part of the boilerplate:

```javascript
if (ENVIRONMENT_IS_NODE) {
[...]
  process['on']('uncaughtException', function(ex) {
    // suppress ExitStatus exceptions from showing an error
    if (!(ex instanceof ExitStatus)) {
      throw ex;
    }
  });
...
}
``` 

So I'm not sure that this is something we can avoid.

**Comment by BatikhSouri** [comment]
It seems that it's [something](https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html#c-exceptions) that could be [disabled](https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html#advanced-compiler-settings). Or am I reading it wrong?

**Comment by jedisct1** [comment]
`DISABLE_EXCEPTION_CATCHING=0` is already set when compiling the library, but I think it is only relevant to C++ code and only affects code generation, not the stub that gets added unconditionally.

**Comment by juhoojala** [comment]
Thanks guys for the responses.

Has anyone come up with even a workaround? I would imagine that this would block many people from using libsodium altogether.

**Comment by mechanicalchopsticks** [comment]
Hello,

No updates to this one? it is really making us think twice about using libsodium, it kind of makes our logs useless.

**Comment by jedisct1** [comment]
Try
```js
process.removeAllListeners("uncaughtException")
```

**Comment by BatikhSouri** [comment]
Worked for me on Node v0.10, v5 & v6. Called `process.removeAllListeners()` right after `require('libsodium-wrappers')`.

**Comment by mechanicalchopsticks** [comment]
Worked for me too, thanks
