### ISSUE TITLE
crypto_box_seal aborts with "Cannot enlarge memory arrays."

### ISSUE THREAD

**Issue by nshtg** [jedisct1/libsodium.js#67]
Hello,

I am using libsodium.js to encrypt answers from a secure backend server.

I am reading a binary file from disk (as base64), try to encrypt it with crypto_box_seal and send it back to the user (again as base64).

When the file is 5337kb everything works fine, as soon as the file is 5800kb libsodium.js will trigger this abort:

```
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_ME
MORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program run
s, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
Unhandled rejection abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2
) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher v
alue before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
  at jsStackTrace (/var/www/hello.world/node_modules/libsodium/dist/modules/libsodium.js:13:15866)
  at stackTrace (/var/www/hello.world/node_modules/libsodium/dist/modules/libsodium.js:13:16037)
  at abort (/var/www/hello.world/node_modules/libsodium/dist/modules/libsodium.js:26:15122)
  at abortOnCannotGrowMemory (/var/www/hello.world/node_modules/libsodium/dist/modules/libsodium.js:13:16918)
  at enlargeMemory (/var/www/hello.world/node_modules/libsodium/dist/modules/libsodium.js:13:17363)
  at Function.Runtime.dynamicAlloc [as alloc] (/var/www/hello.world/node_modules/libsodium/dist/modules/libsodium.js:13:7173)
  at _sbrk (/var/www/hello.world/node_modules/libsodium/dist/modules/libsodium.js:13:197184)
  at Object.bc [as _malloc] (/var/www/hello.world/node_modules/libsodium/dist/modules/libsodium.js:18:168615)
  at _malloc (/var/www/hello.world/node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js:356:32)
  at _to_allocated_buf_address (/var/www/hello.world/node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js:350:23)
  at Object.crypto_box_seal (/var/www/hello.world/node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js:1631:25)
  at Socket.module.exports.Socket.encrypt (/var/www/hello.world/crypto.coffee:23:21)
  at Socket.encrypt (/var/www/hello.world/crypto.coffee:1:1)
  at /var/www/hello.world/handler.coffee:108:22
  at tryCatcher (/var/www/hello.world/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/var/www/hello.world/node_modules/bluebird/js/release/promise.js:504:31)
  at Promise._settlePromise (/var/www/hello.world/node
```

I can see the memory consumption spike up to roughly 300mb then the script crashes. The server has plenty (2GB) of ram, most of it is unused.

Is this a wanted behaviour?

Btw, have you tested version 0.4.0 of libsodium from npm? I am no longer able to install the newest version using npm:

```
$ npm i libsodium-wrappers@latest
npm WARN install:libsodium@0.4.0 ENOENT: no such file or directory, open '/var/www/hello.world/node_modules/.staging/libsodium-c18b7999/package.json'
npm WARN node-backend-v2@1.0.0 No description
npm WARN node-backend-v2@1.0.0 No repository field.
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/home/hans/.npm-packages/bin/npm" "i" "libsodium-wrappers@latest"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! path /var/www/hello.world/node_modules/.staging/libsodium-wrappers-26114998/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/www/hello.world/node_modules/.staging/libsodium-wrappers-26114998/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/var/www/hello.world/node_modules/.staging/libsodium-wrappers-26114998/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/hello.world/npm-debug.log
```

Greetings

**Comment by nshtg** [comment]
Note: The newest v0.4.0 sumo version (copied from this repo since `npm install` is not working) works with files that are >10mb.

**Comment by nshtg** [comment]
I was encrypting a file that was 5.8mb in total, not gigabytes.
