### ISSUE TITLE
libsodium-wrappers-sumo npm package 0.4.6 contains no code

### ISSUE THREAD

**Issue by abovethewater** [jedisct1/libsodium.js#70]
npm / yarn install of latest

    yarn add libsodium-wrappers-sumo --save
    yarn add v0.15.1
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 📃  Building fresh packages...
    success Saved lockfile.
    success Saved 2 new dependencies.
    ├─ libsodium-wrappers-sumo@0.4.6
    └─ libsodium@0.4.6
    ✨  Done in 2.45s.

But requiring the module:

    sodium = require('libsodium-wrappers-sumo')

 produces the following:

    Error: Cannot find module 'libsodium-wrappers-sumo'
      at Function.Module._resolveFilename (module.js:455:15)
      at Function.Module._load (module.js:403:25)
      at Module.require (module.js:483:17)
      at require (internal/module.js:20:19)

Looking at the node_modules directory, there appears to be no code included

  ls node_modules/libsodium-wrappers-sumo/
  LICENSE		README.md	package.json

The package.json references a dist directory which doesn't exist.

Everything works nicely if installed manually direct from repo.

**Comment by jedisct1** [comment]
Should be good now. ლ( ◕ 益 ◕ ) ლ

**Comment by abovethewater** [comment]
Confirmed all good, thanks for the quick response.
