### ISSUE TITLE
crypto_scalarmult() supports degenerate public keys

### ISSUE THREAD

**Issue by ffflorian** [jedisct1/libsodium.js#76]
Following sodiumoxide's issue https://github.com/dnaq/sodiumoxide/issues/154, libsodium.js also currently accepts all-zero public keys in `crypto_scalarmult()` even though it's checking libsodium's `crypto_scalarmult()` return value.

Maybe the transpiler didn't add the correct return value?

**Comment by jedisct1** [comment]
Hi Florian,

Do you have test code to reproduce this?

```js
let sodium = require('libsodium-wrappers');
sodium.crypto_scalarmult(new Uint8Array(32), new Uint8Array(32));
```

This throws an exception here:
```
/Users/j/src/libsodium.js/dist/modules/libsodium-wrappers.js:378
        throw new Error(err);
        ^

Error
    at _free_and_throw_error (/Users/j/src/libsodium.js/dist/modules/libsodium-wrappers.js:378:15)
    at Object.crypto_scalarmult (/Users/j/src/libsodium.js/dist/modules/libsodium-wrappers.js:2494:3)
    at Object.<anonymous> (/Users/j/src/libsodium.js/dist/modules/test.js:2:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```

**Comment by ffflorian** [comment]
@jedisct1 You are right, it seems like this is a problem of our slightly adjusted implementation. Thank you for clarifying!
